.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel jumptable
/* 312E0 800306E0 */ .word func_8000E4D0
/* 312E4 800306E4 */ .word func_8000E4F0
/* 312E8 800306E8 */ .word func_8000E520
/* 312EC 800306EC */ .word func_8000E544
/* 312F0 800306F0 */ .word func_8000E550
/* 312F4 800306F4 */ .word func_8000E678
/* 312F8 800306F8 */ .word func_8000E768
/* 312FC 800306FC */ .word func_8000E754
/* 31300 80030700 */ .word func_8000E78C
/* 31304 80030704 */ .word func_8000E7F4
/* 31308 80030708 */ .word func_8000E860
/* 3130C 8003070C */ .word func_8000E870
/* 31310 80030710 */ .word func_8000E8A0
/* 31314 80030714 */ .word func_8000E8B0
/* 31318 80030718 */ .word func_8000E8C0
/* 3131C 8003071C */ .word func_8000E8D0
/* 31320 80030720 */ .word func_8000E924
/* 31324 80030724 */ .word func_8000E984
/* 31328 80030728 */ .word func_8000E994
/* 3132C 8003072C */ .word func_8000E9A0
/* 31330 80030730 */ .word func_8000E9B0
/* 31334 80030734 */ .word func_8000E9BC
/* 31338 80030738 */ .word func_8000EA28
/* 3133C 8003073C */ .word func_8000EABC
/* 31340 80030740 */ .word func_8000EAE4
/* 31344 80030744 */ .word func_8000EAF0
/* 31348 80030748 */ .word func_8000EB00
/* 3134C 8003074C */ .word func_8000EB0C
/* 31350 80030750 */ .word func_8000EB20
/* 31354 80030754 */ .word func_8000EB34
/* 31358 80030758 */ .word func_8000EB3C
/* 3135C 8003075C */ .word func_8000EB84
/* 31360 80030760 */ .word func_8000EB90
/* 31364 80030764 */ .word func_8000EB98
/* 31368 80030768 */ .word func_8000EC08
/* 3136C 8003076C */ .word func_8000EC18
/* 31370 80030770 */ .word func_8000EC68
/* 31374 80030774 */ .word func_8000ECB8
/* 31378 80030778 */ .word func_8000ED08
/* 3137C 8003077C */ .word func_8000ED18
/* 31380 80030780 */ .word func_8000EDEC
/* 31384 80030784 */ .word func_8000EE24
/* 31388 80030788 */ .word func_8000EE34
/* 3138C 8003078C */ .word func_8000EE78
/* 31390 80030790 */ .word func_8000EEE8
