[project]
name = "lego-racers"
version = "0.1.0"
requires-python = ">=3.12"


[tool.black]
line-length = 120
extend-exclude = '''
(
  ^/ninja_syntax.py    # exclude a file named foo.py in the root of the project
)
'''
