.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_8003BCE0
/* 33010 8003BCE0 3F800000 */ .float 1

glabel D_8003BCE4
/* 33014 8003BCE4 3F800000 */ .float 1

glabel D_8003BCE8
/* 33018 8003BCE8 437F0000 */ .float 255
