.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_80082810
/* 79B40 80082810 */ .word 0xFFFFFFFF

glabel D_80082814
/* 79B44 80082814 */ .word 0x00000000

glabel D_80082818
/* 79B48 80082818 */ .word 0x00000000

glabel D_8008281C
/* 79B4C 8008281C */ .word 0x00000000

glabel D_80082820
/* 79B50 80082820 */ .word 0x00000000

glabel D_80082824
/* 79B54 80082824 */ .word 0x00000000

glabel D_80082828
/* 79B58 80082828 */ .word 0x00000000

glabel D_8008282C
/* 79B5C 8008282C */ .word 0x00000000
/* 79B60 80082830 */ .word 0x00000001
/* 79B64 80082834 */ .word 0x00000002
