.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_800827F0
/* 79B20 800827F0 */ .word 0x00000001
/* 79B24 800827F4 */ .word 0x00000002

glabel D_800827F8
/* 79B28 800827F8 */ .word D_8003C1F0

glabel D_800827FC
/* 79B2C 800827FC */ .word 0xFFFFFFFF

glabel D_80082800
/* 79B30 80082800 */ .word 0xFFFFFFFF
