.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.0 */

glabel D_8003C2A0
/* 335D0 8003C2A0 */ .asciz "%s,\nfile %s, line %d"
                      .balign 4

glabel D_8003C2B8
/* 335E8 8003C2B8 */ .asciz "Invalid error condition"
                      .balign 4

glabel D_8003C2D0
/* 33600 8003C2D0 */ .asciz "General error occurred"
                      .balign 4

glabel D_8003C2E8
/* 33618 8003C2E8 */ .asciz "Invalid parameter detected"
                      .balign 4

glabel D_8003C304
/* 33634 8003C304 */ .asciz "Invalid value detected"
                      .balign 4

glabel D_8003C31C
/* 3364C 8003C31C */ .asciz "Out of memory error occured"
                      .balign 4

glabel D_8003C338
/* 33668 8003C338 */ .asciz "Critical resource busy"
                      .balign 4

glabel D_8003C350
/* 33680 8003C350 */ .asciz "Assertion Failed"
                      .balign 4

glabel D_8003C364
/* 33694 8003C364 */ .asciz "Unknown error condition occured"
                      .balign 4
/* 336B4 8003C384 */ .asciz ""
                      .balign 4

glabel jtbl_8003C388
/* 336B8 8003C388 80046BE8 */ .word L80046BE8
/* 336BC 8003C38C 80046BF4 */ .word L80046BF4
/* 336C0 8003C390 80046BDC */ .word L80046BDC
/* 336C4 8003C394 80046BD0 */ .word L80046BD0
/* 336C8 8003C398 80046BC4 */ .word L80046BC4
/* 336CC 8003C39C 80046BB8 */ .word L80046BB8
/* 336D0 8003C3A0 80046BAC */ .word L80046BAC
/* 336D4 8003C3A4 80046BA0 */ .word L80046BA0
