.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_80082850
/* 79B80 80082850 */ .word 0xFFFFFFFF

glabel D_80082854
/* 79B84 80082854 */ .word 0x00000000

glabel D_80082858
/* 79B88 80082858 */ .word 0x8003C9E0
