.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_80083D20
/* 7B050 80083D20 */ .byte 0x08
/* 7B051 80083D21 */ .byte 0x08
/* 7B052 80083D22 */ .byte 0x08
/* 7B053 80083D23 */ .byte 0xFF
