.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_8003CE20
/* 34150 8003CE20 00000000 */ .word 0x00000000
/* 34154 8003CE24 00000000 */ .word 0x00000000
/* 34158 8003CE28 00000000 */ .word 0x00000000
/* 3415C 8003CE2C 800547B4 */ .word func_800547B4
