.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.0 */

glabel D_8003D4F0
/* 34820 8003D4F0 00000000 */ .word 0x00000000

glabel D_8003D4F4
/* 34824 8003D4F4 */ .asciz ": Duplicate name encountered"
                      .balign 4
/* 34844 8003D514 */ .asciz ""
                      .balign 4

glabel D_8003D518
/* 34848 8003D518 00000000 */ .word 0x00000000
/* 3484C 8003D51C 00000000 */ .word 0x00000000
/* 34850 8003D520 00000000 */ .word 0x00000000
/* 34854 8003D524 80058E0C */ .word func_80058E0C
/* 34858 8003D528 00000000 */ .word 0x00000000
/* 3485C 8003D52C 80058E5C */ .word func_80058E5C
/* 34860 8003D530 00000000 */ .word 0x00000000
/* 34864 8003D534 80058EE4 */ .word func_80058EE4
