.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_800404E0
/* 37810 800404E0 3F800000 */ .float 1

glabel D_800404E4
/* 37814 800404E4 43AB8000 */ .float 343

glabel D_800404E8
/* 37818 800404E8 432B8000 */ .float 171.5
