.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CA7D0
/* 80B90 800CA7D0 40C90FDB */ .float 6.283185482

glabel D_race_800CA7D4
/* 80B94 800CA7D4 3FC90FDB */ .float 1.570796371

glabel D_race_800CA7D8
/* 80B98 800CA7D8 3F800000 */ .float 1

glabel D_race_800CA7DC
/* 80B9C 800CA7DC 3FC90FDB */ .float 1.570796371

glabel D_race_800CA7E0
/* 80BA0 800CA7E0 BF800000 */ .float -1

glabel D_race_800CA7E4
/* 80BA4 800CA7E4 40C90FDB */ .float 6.283185482

glabel D_race_800CA7E8
/* 80BA8 800CA7E8 3FC90FDB */ .float 1.570796371

glabel D_race_800CA7EC
/* 80BAC 800CA7EC 3F800000 */ .float 1

glabel D_race_800CA7F0
/* 80BB0 800CA7F0 3E22F983 */ .float 0.1591549367

glabel D_race_800CA7F4
/* 80BB4 800CA7F4 3FC90FDB */ .float 1.570796371

glabel D_race_800CA7F8
/* 80BB8 800CA7F8 40490FDB */ .float 3.141592741

glabel D_race_800CA7FC
/* 80BBC 800CA7FC 3F800000 */ .float 1

glabel D_race_800CA800
/* 80BC0 800CA800 BF800000 */ .float -1

glabel D_race_800CA804
/* 80BC4 800CA804 3F800000 */ .float 1
