.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CA810
/* 80BD0 800CA810 3F800000 */ .float 1

glabel D_race_800CA814
/* 80BD4 800CA814 3F800000 */ .float 1

glabel D_race_800CA818
/* 80BD8 800CA818 00000000 */ .word 0x00000000
/* 80BDC 800CA81C 00000000 */ .word 0x00000000
/* 80BE0 800CA820 00000000 */ .word 0x00000000
/* 80BE4 800CA824 800D0D58 */ .word func_race_800D0D58
