.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CA830
/* 80BF0 800CA830 3F800000 */ .float 1

glabel D_race_800CA834
/* 80BF4 800CA834 41700000 */ .float 15

glabel D_race_800CA838
/* 80BF8 800CA838 437F0000 */ .float 255

glabel D_race_800CA83C
/* 80BFC 800CA83C 3F800000 */ .float 1

glabel D_race_800CA840
/* 80C00 800CA840 3F800000 */ .float 1

glabel D_race_800CA844
/* 80C04 800CA844 437F0000 */ .float 255

glabel D_race_800CA848
/* 80C08 800CA848 3DCCCCCD */ .float 0.1000000015

glabel D_race_800CA84C
/* 80C0C 800CA84C BF800000 */ .float -1

glabel D_race_800CA850
/* 80C10 800CA850 3F000000 */ .float 0.5

glabel D_race_800CA854
/* 80C14 800CA854 C0C00000 */ .float -6

glabel D_race_800CA858
/* 80C18 800CA858 3E800000 */ .float 0.25
/* 80C1C 800CA85C 00000000 */ .float 0

glabel D_race_800CA860
/* 80C20 800CA860 00000000 */ .word 0x00000000
/* 80C24 800CA864 00000000 */ .word 0x00000000
/* 80C28 800CA868 00000000 */ .word 0x00000000
/* 80C2C 800CA86C 800D1254 */ .word func_race_800D1254
