.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CA870
/* 80C30 800CA870 00000000 */ .word 0x00000000
/* 80C34 800CA874 00000000 */ .word 0x00000000

glabel D_race_800CA878
/* 80C38 800CA878 00000000 */ .word 0x00000000
/* 80C3C 800CA87C 00000000 */ .word 0x00000000
/* 80C40 800CA880 00000000 */ .word 0x00000000
/* 80C44 800CA884 800D218C */ .word func_race_800D218C
