.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CA9B0
/* 80D70 800CA9B0 3F800000 */ .float 1

glabel D_race_800CA9B4
/* 80D74 800CA9B4 3D000000 */ .float 0.03125

glabel D_race_800CA9B8
/* 80D78 800CA9B8 3F800000 */ .float 1

glabel D_race_800CA9BC
/* 80D7C 800CA9BC BF800000 */ .float -1

glabel D_race_800CA9C0
/* 80D80 800CA9C0 00000000 */ .word 0x00000000
/* 80D84 800CA9C4 00000000 */ .word 0x00000000
/* 80D88 800CA9C8 3F800000 */ .word 0x3F800000

glabel D_race_800CA9CC
/* 80D8C 800CA9CC 3F800000 */ .float 1

glabel D_race_800CA9D0
/* 80D90 800CA9D0 BF800000 */ .float -1

glabel D_race_800CA9D4
/* 80D94 800CA9D4 42000000 */ .float 32

glabel D_race_800CA9D8
/* 80D98 800CA9D8 3F800000 */ .float 1

glabel D_race_800CA9DC
/* 80D9C 800CA9DC 3CA3D70A */ .float 0.01999999955

glabel D_race_800CA9E0
/* 80DA0 800CA9E0 42000000 */ .float 32

glabel D_race_800CA9E4
/* 80DA4 800CA9E4 42000000 */ .float 32

glabel D_race_800CA9E8
/* 80DA8 800CA9E8 3CA3D70A */ .float 0.01999999955

glabel D_race_800CA9EC
/* 80DAC 800CA9EC 3F000000 */ .float 0.5
