.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CAA30
/* 80DF0 800CAA30 00000000 */ .word 0x00000000
/* 80DF4 800CAA34 00000000 */ .word 0x00000000

glabel D_race_800CAA38
/* 80DF8 800CAA38 00000000 */ .word 0x00000000
/* 80DFC 800CAA3C 00000000 */ .word 0x00000000
/* 80E00 800CAA40 00000000 */ .word 0x00000000
/* 80E04 800CAA44 800D5BDC */ .word func_race_800D5BDC
