.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_801320D0
/* E8490 801320D0 */ .word 0x00000000
/* E8494 801320D4 */ .word 0x00000000
/* E8498 801320D8 */ .word 0x00000000
/* E849C 801320DC */ .word 0x00000000
/* E84A0 801320E0 */ .word 0x00000000
/* E84A4 801320E4 */ .word 0x00000000
