.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CB360
/* 81720 800CB360 00000000 */ .word 0x00000000
/* 81724 800CB364 00000000 */ .word 0x00000000
/* 81728 800CB368 00000000 */ .word 0x00000000
/* 8172C 800CB36C 800DEBA4 */ .word func_race_800DEBA4
/* 81730 800CB370 00000000 */ .word 0x00000000
/* 81734 800CB374 800DE924 */ .word func_race_800DE924
