.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_race_80132100
/* E84C0 80132100 */ .word 0x00000001

glabel D_race_80132104
/* E84C4 80132104 */ .word 0x00000002

glabel D_race_80132108
/* E84C8 80132108 */ .word 0x3F800000
/* E84CC 8013210C */ .word 0x00000000
/* E84D0 80132110 */ .word 0x00000000
/* E84D4 80132114 */ .word 0x00000000
/* E84D8 80132118 */ .word 0x3F800000
/* E84DC 8013211C */ .word 0x00000000
/* E84E0 80132120 */ .word 0x00000000
/* E84E4 80132124 */ .word 0x00000000
/* E84E8 80132128 */ .word 0x3F800000
