.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CB900
/* 81CC0 800CB900 00000000 */ .word 0x00000000
/* 81CC4 800CB904 00000000 */ .word 0x00000000
/* 81CC8 800CB908 00000000 */ .word 0x00000000
/* 81CCC 800CB90C 800E4F30 */ .word func_race_800E4F30
/* 81CD0 800CB910 00000000 */ .word 0x00000000
/* 81CD4 800CB914 800E4DB8 */ .word func_race_800E4DB8
