.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CB930
/* 81CF0 800CB930 00000000 */ .word 0x00000000

glabel D_race_800CB934
/* 81CF4 800CB934 3FA00000 */ .float 1.25

glabel D_race_800CB938
/* 81CF8 800CB938 3F800000 */ .float 1

glabel D_race_800CB93C
/* 81CFC 800CB93C 3F800000 */ .float 1

glabel D_race_800CB940
/* 81D00 800CB940 3C23D70A */ .float 0.009999999776

glabel D_race_800CB944
/* 81D04 800CB944 3F800000 */ .float 1

glabel D_race_800CB948
/* 81D08 800CB948 447A0000 */ .float 1000

glabel D_race_800CB94C
/* 81D0C 800CB94C 44FA0000 */ .float 2000

glabel D_race_800CB950
/* 81D10 800CB950 40800000 */ .float 4

glabel D_race_800CB954
/* 81D14 800CB954 3F000000 */ .float 0.5

glabel D_race_800CB958
/* 81D18 800CB958 7CF0BDC2 */ .float 9.999999934e+36
