.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_80132170
/* E8530 80132170 */ .word 0x44104000
/* E8534 80132174 */ .word 0xC3DE0000
/* E8538 80132178 */ .word 0x40EAB021
/* E853C 8013217C */ .word 0x44174000
/* E8540 80132180 */ .word 0xC3FA0000
/* E8544 80132184 */ .word 0x41980000
/* E8548 80132188 */ .word 0x44034000
/* E854C 8013218C */ .word 0xC3FC8000
/* E8550 80132190 */ .word 0x40933333
