.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CCD00
/* 830C0 800CCD00 41A00000 */ .float 20

glabel D_race_800CCD04
/* 830C4 800CCD04 3E4CCCCD */ .float 0.200000003

glabel D_race_800CCD08
/* 830C8 800CCD08 3CA3D70A */ .float 0.01999999955

glabel D_race_800CCD0C
/* 830CC 800CCD0C 41A00000 */ .float 20
