.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_race_801321D0
/* E8590 801321D0 */ .word D_race_800CCEC0

glabel D_race_801321D4
/* E8594 801321D4 */ .word 0x800CCECC
