.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CD000
/* 833C0 800CD000 43FA0000 */ .float 500

glabel D_race_800CD004
/* 833C4 800CD004 40C90FDB */ .float 6.283185482

glabel D_race_800CD008
/* 833C8 800CD008 4322F983 */ .float 162.9746552

glabel D_race_800CD00C
/* 833CC 800CD00C 42800000 */ .float 64

glabel D_race_800CD010
/* 833D0 800CD010 3F800000 */ .float 1
