.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CD410
/* 837D0 800CD410 47414D45 */ .word 0x47414D45
/* 837D4 800CD414 44415441 */ .word 0x44415441
/* 837D8 800CD418 5C434F4D */ .word 0x5C434F4D
/* 837DC 800CD41C 4D4F4E00 */ .word 0x4D4F4E00

glabel D_race_800CD420
/* 837E0 800CD420 */ .asciz "GAMEDATA\\"
                      .balign 4
