.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_801321E0
/* E85A0 801321E0 */ .word 0xFFFFFFFF

glabel D_race_801321E4
/* E85A4 801321E4 */ .word D_race_800CD430
