.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CD590
/* 83950 800CD590 3F800000 */ .float 1

glabel D_race_800CD594
/* 83954 800CD594 BF800000 */ .float -1

glabel D_race_800CD598
/* 83958 800CD598 3A83126F */ .float 0.001000000047

glabel D_race_800CD59C
/* 8395C 800CD59C 41300000 */ .float 11

glabel D_race_800CD5A0
/* 83960 800CD5A0 41800000 */ .float 16

glabel D_race_800CD5A4
/* 83964 800CD5A4 4084CCCD */ .float 4.150000095

glabel D_race_800CD5A8
/* 83968 800CD5A8 3FA00000 */ .float 1.25

glabel D_race_800CD5AC
/* 8396C 800CD5AC 41CA0000 */ .float 25.25

glabel D_race_800CD5B0
/* 83970 800CD5B0 C1CA0000 */ .float -25.25

glabel D_race_800CD5B4
/* 83974 800CD5B4 3F800000 */ .float 1

glabel D_race_800CD5B8
/* 83978 800CD5B8 BF800000 */ .float -1

glabel D_race_800CD5BC
/* 8397C 800CD5BC 3F800000 */ .float 1

glabel D_race_800CD5C0
/* 83980 800CD5C0 3F000000 */ .float 0.5

glabel D_race_800CD5C4
/* 83984 800CD5C4 3EE66666 */ .float 0.4499999881

glabel D_race_800CD5C8
/* 83988 800CD5C8 3F800000 */ .float 1

glabel D_race_800CD5CC
/* 8398C 800CD5CC 3F000000 */ .float 0.5

glabel D_race_800CD5D0
/* 83990 800CD5D0 3EE66666 */ .float 0.4499999881

glabel D_race_800CD5D4
/* 83994 800CD5D4 C1CA0000 */ .float -25.25

glabel D_race_800CD5D8
/* 83998 800CD5D8 41CA0000 */ .float 25.25

glabel D_race_800CD5DC
/* 8399C 800CD5DC 3F800000 */ .float 1

glabel D_race_800CD5E0
/* 839A0 800CD5E0 BF800000 */ .float -1

glabel D_race_800CD5E4
/* 839A4 800CD5E4 3F800000 */ .float 1

glabel D_race_800CD5E8
/* 839A8 800CD5E8 3F000000 */ .float 0.5
