.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_80132200
/* E85C0 80132200 */ .word 0x00000040
/* E85C4 80132204 */ .word 0x00000020

glabel D_race_80132208
/* E85C8 80132208 */ .word 0x00000005
/* E85CC 8013220C */ .word 0x00000005

glabel D_race_80132210
/* E85D0 80132210 */ .word 0x3F000000

glabel D_race_80132214
/* E85D4 80132214 */ .word 0x3C23D70A
/* E85D8 80132218 */ .word 0x3EFAE148
/* E85DC 8013221C */ .word 0x3EFAE148

glabel D_race_80132220
/* E85E0 80132220 */ .word 0x000E000F
/* E85E4 80132224 */ .short 0x0011

glabel D_race_80132226
/* E85E6 80132226 */ .short 0x0014

glabel D_race_80132228
/* E85E8 80132228 */ .word 0x000E0010
/* E85EC 8013222C */ .word 0x00110000

glabel D_race_80132230
/* E85F0 80132230 */ .word 0x00120013

glabel D_race_80132234
/* E85F4 80132234 */ .short 0x0015

glabel D_race_80132236
/* E85F6 80132236 */ .short 0x0016

glabel D_race_80132238
/* E85F8 80132238 */ .short 0x0017

glabel D_race_8013223A
/* E85FA 8013223A */ .short 0x0018

glabel D_race_8013223C
/* E85FC 8013223C */ .short 0x002C
/* E85FE 8013223E */ .short 0x0000
