.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CDC90
/* 84050 800CDC90 BF800000 */ .float -1

glabel D_race_800CDC94
/* 84054 800CDC94 BF800000 */ .float -1

glabel D_race_800CDC98
/* 84058 800CDC98 3F800000 */ .float 1

glabel D_race_800CDC9C
/* 8405C 800CDC9C 3F733333 */ .float 0.9499999881

glabel D_race_800CDCA0
/* 84060 800CDCA0 3F866666 */ .float 1.049999952
