.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_race_80132240
/* E8600 80132240 */ .word D_race_800CDCF0

glabel D_race_80132244
/* E8604 80132244 */ .word 0x800CDCF8

glabel D_race_80132248
/* E8608 80132248 */ .word 0x800CDD00

glabel D_race_8013224C
/* E860C 8013224C */ .word 0xFFFFFFFF

glabel D_race_80132250
/* E8610 80132250 */ .word 0x00000001

glabel D_race_80132254
/* E8614 80132254 */ .word 0x00000002

glabel D_race_80132258
/* E8618 80132258 */ .word 0x00000003

glabel D_race_8013225C
/* E861C 8013225C */ .word 0xFFFFFFFF

glabel D_race_80132260
/* E8620 80132260 */ .word 0xFFFFFFFF
