.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CDE50
/* 84210 800CDE50 BF800000 */ .float -1

glabel D_race_800CDE54
/* 84214 800CDE54 736B6964 */ .word 0x736B6964
/* 84218 800CDE58 00000000 */ .word 0x00000000

glabel D_race_800CDE5C
/* 8421C 800CDE5C */ .asciz "trbskid"
                      .balign 4

glabel D_race_800CDE64
/* 84224 800CDE64 BF800000 */ .float -1

glabel D_race_800CDE68
/* 84228 800CDE68 */ .asciz "tiresmk"
                      .balign 4

glabel D_race_800CDE70
/* 84230 800CDE70 */ .asciz "dust"
                      .balign 4

glabel D_race_800CDE78
/* 84238 800CDE78 */ .asciz "carsmke"
                      .balign 4

glabel D_race_800CDE80
/* 84240 800CDE80 3F000000 */ .float 0.5

glabel D_race_800CDE84
/* 84244 800CDE84 40000000 */ .float 2

glabel D_race_800CDE88
/* 84248 800CDE88 6361726C */ .word 0x6361726C
/* 8424C 800CDE8C 616E6400 */ .word 0x616E6400

glabel D_race_800CDE90
/* 84250 800CDE90 3F19999A */ .float 0.6000000238

glabel D_race_800CDE94
/* 84254 800CDE94 43960000 */ .float 300

glabel D_race_800CDE98
/* 84258 800CDE98 3F800000 */ .float 1

glabel D_race_800CDE9C
/* 8425C 800CDE9C 3F000000 */ .float 0.5

glabel D_race_800CDEA0
/* 84260 800CDEA0 40000000 */ .float 2

glabel D_race_800CDEA4
/* 84264 800CDEA4 BF800000 */ .float -1

glabel D_race_800CDEA8
/* 84268 800CDEA8 C1F00000 */ .float -30

glabel D_race_800CDEAC
/* 8426C 800CDEAC 3C23D70A */ .float 0.009999999776

glabel D_race_800CDEB0
/* 84270 800CDEB0 BF800000 */ .float -1

glabel D_race_800CDEB4
/* 84274 800CDEB4 3D4CCCCD */ .float 0.05000000075

glabel D_race_800CDEB8
/* 84278 800CDEB8 3C23D70A */ .float 0.009999999776

glabel D_race_800CDEBC
/* 8427C 800CDEBC 3E4CCCCD */ .float 0.200000003

glabel D_race_800CDEC0
/* 84280 800CDEC0 BE4CCCCD */ .float -0.200000003

glabel D_race_800CDEC4
/* 84284 800CDEC4 BE4CCCCD */ .float -0.200000003

glabel D_race_800CDEC8
/* 84288 800CDEC8 BF19999A */ .float -0.6000000238
/* 8428C 800CDECC 00000000 */ .float 0

glabel D_race_800CDED0
/* 84290 800CDED0 41F0000000000000 */ .double 4294967296

glabel D_race_800CDED8
/* 84298 800CDED8 3BCDE32E */ .float 0.006283185445

glabel D_race_800CDEDC
/* 8429C 800CDEDC 4322F983 */ .float 162.9746552

glabel D_race_800CDEE0
/* 842A0 800CDEE0 40C00000 */ .float 6

glabel D_race_800CDEE4
/* 842A4 800CDEE4 41100000 */ .float 9

glabel D_race_800CDEE8
/* 842A8 800CDEE8 3DCCCCCD */ .float 0.1000000015

glabel D_race_800CDEEC
/* 842AC 800CDEEC 3F800000 */ .float 1

glabel D_race_800CDEF0
/* 842B0 800CDEF0 447A0000 */ .float 1000

glabel D_race_800CDEF4
/* 842B4 800CDEF4 3F2A7EFA */ .float 0.6660000086

glabel D_race_800CDEF8
/* 842B8 800CDEF8 3C23D70A */ .float 0.009999999776

glabel D_race_800CDEFC
/* 842BC 800CDEFC 3D872B02 */ .float 0.06599999964

glabel D_race_800CDF00
/* 842C0 800CDF00 BF800000 */ .float -1

glabel D_race_800CDF04
/* 842C4 800CDF04 3F800000 */ .float 1

glabel D_race_800CDF08
/* 842C8 800CDF08 41700000 */ .float 15

glabel D_race_800CDF0C
/* 842CC 800CDF0C 40C00000 */ .float 6

glabel D_race_800CDF10
/* 842D0 800CDF10 451C4000 */ .float 2500

glabel D_race_800CDF14
/* 842D4 800CDF14 461C4000 */ .float 10000

glabel D_race_800CDF18
/* 842D8 800CDF18 45EA6000 */ .float 7500

glabel D_race_800CDF1C
/* 842DC 800CDF1C 433F0000 */ .float 191

glabel D_race_800CDF20
/* 842E0 800CDF20 3F933333 */ .float 1.149999976

glabel D_race_800CDF24
/* 842E4 800CDF24 BF800000 */ .float -1
