.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CE520
/* 848E0 800CE520 3F800000 */ .float 1

glabel D_race_800CE524
/* 848E4 800CE524 3F800000 */ .float 1
