.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CE530
/* 848F0 800CE530 */ .asciz "brick1"
                      .balign 4
/* 848F8 800CE538 */ .asciz "brick2"
                      .balign 4
/* 84900 800CE540 */ .asciz "brick3"
                      .balign 4
/* 84908 800CE548 */ .asciz "brick4"
                      .balign 4
