.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_race_80132470
/* E8830 80132470 */ .word 0x63616E73
/* E8834 80132474 */ .word 0x74726B00

glabel D_race_80132478
/* E8838 80132478 */ .word 0x323232C8
