.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_80132490
/* E8850 80132490 */ .word 0x643C0EFF

glabel D_race_80132494
/* E8854 80132494 */ .word 0x8F5A1CFF

glabel D_race_80132498
/* E8858 80132498 */ .word 0x141400FF
