.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_race_801324A0
/* E8860 801324A0 */ .word 0x6D736C73
/* E8864 801324A4 */ .word 0x74726B00

glabel D_race_801324A8
/* E8868 801324A8 */ .word 0xFFFFFFC8
