.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CECD0
/* 85090 800CECD0 */ .asciz "turbo3"
                      .balign 4

glabel D_race_800CECD8
/* 85098 800CECD8 3F800000 */ .float 1

glabel D_race_800CECDC
/* 8509C 800CECDC 00000000 */ .word 0x00000000

glabel D_race_800CECE0
/* 850A0 800CECE0 */ .asciz ".pwb"
                      .balign 4

glabel D_race_800CECE8
/* 850A8 800CECE8 471C4000 */ .float 40000

glabel D_race_800CECEC
/* 850AC 800CECEC 48742400 */ .float 250000

glabel D_race_800CECF0
/* 850B0 800CECF0 471C4000 */ .float 40000

glabel D_race_800CECF4
/* 850B4 800CECF4 48742400 */ .float 250000

glabel D_race_800CECF8
/* 850B8 800CECF8 471C4000 */ .float 40000

glabel D_race_800CECFC
/* 850BC 800CECFC 48742400 */ .float 250000

glabel D_race_800CED00
/* 850C0 800CED00 471C4000 */ .float 40000

glabel D_race_800CED04
/* 850C4 800CED04 48742400 */ .float 250000

glabel D_race_800CED08
/* 850C8 800CED08 */ .asciz "gen"
                      .balign 4

glabel D_race_800CED0C
/* 850CC 800CED0C */ .asciz "genblen"
                      .balign 4

glabel D_race_800CED14
/* 850D4 800CED14 */ .asciz "pbrickP"
                      .balign 4

glabel D_race_800CED1C
/* 850DC 800CED1C */ .asciz "ptrailP"
                      .balign 4

glabel D_race_800CED24
/* 850E4 800CED24 */ .asciz "pbrickM"
                      .balign 4

glabel D_race_800CED2C
/* 850EC 800CED2C */ .asciz "ptrailM"
                      .balign 4

glabel D_race_800CED34
/* 850F4 800CED34 */ .asciz "pbrickS"
                      .balign 4

glabel D_race_800CED3C
/* 850FC 800CED3C */ .asciz "ptrailS"
                      .balign 4

glabel D_race_800CED44
/* 85104 800CED44 */ .asciz "pbrickT"
                      .balign 4

glabel D_race_800CED4C
/* 8510C 800CED4C */ .asciz "ptrailT"
                      .balign 4
/* 85114 800CED54 */ .asciz ""
                      .balign 4

glabel jtbl_race_800CED58
/* 85118 800CED58 801294BC */ .word Lrace_801294BC
/* 8511C 800CED5C 8012953C */ .word Lrace_8012953C
/* 85120 800CED60 801294E4 */ .word Lrace_801294E4
/* 85124 800CED64 801294F0 */ .word Lrace_801294F0
/* 85128 800CED68 801294FC */ .word Lrace_801294FC
/* 8512C 800CED6C 80129478 */ .word Lrace_80129478
/* 85130 800CED70 80129508 */ .word Lrace_80129508
/* 85134 800CED74 8012953C */ .word Lrace_8012953C
/* 85138 800CED78 80129518 */ .word Lrace_80129518
/* 8513C 800CED7C 8012952C */ .word Lrace_8012952C

glabel D_race_800CED80
/* 85140 800CED80 */ .asciz "enh"
                      .balign 4

glabel D_race_800CED84
/* 85144 800CED84 */ .asciz "enhblen"
                      .balign 4

glabel D_race_800CED8C
/* 8514C 800CED8C 62617272 */ .word 0x62617272
/* 85150 800CED90 656C0000 */ .word 0x656C0000

glabel D_race_800CED94
/* 85154 800CED94 */ .asciz "Explsn"
                      .balign 4

glabel D_race_800CED9C
/* 8515C 800CED9C */ .asciz "exflash"
                      .balign 4

glabel D_race_800CEDA4
/* 85164 800CEDA4 */ .asciz "exscar"
                      .balign 4

glabel D_race_800CEDAC
/* 8516C 800CEDAC */ .asciz "spikexp"
                      .balign 4

glabel D_race_800CEDB4
/* 85174 800CEDB4 3F800000 */ .float 1

glabel D_race_800CEDB8
/* 85178 800CEDB8 41700000 */ .float 15

glabel D_race_800CEDBC
/* 8517C 800CEDBC 40A00000 */ .float 5

glabel D_race_800CEDC0
/* 85180 800CEDC0 41200000 */ .float 10

glabel D_race_800CEDC4
/* 85184 800CEDC4 40A00000 */ .float 5

glabel D_race_800CEDC8
/* 85188 800CEDC8 3B83126F */ .float 0.00400000019

glabel D_race_800CEDCC
/* 8518C 800CEDCC 40C90FDB */ .float 6.283185482

glabel D_race_800CEDD0
/* 85190 800CEDD0 481C4000 */ .float 160000

glabel D_race_800CEDD4
/* 85194 800CEDD4 3F733333 */ .float 0.9499999881

glabel D_race_800CEDD8
/* 85198 800CEDD8 481C4000 */ .float 160000

glabel D_race_800CEDDC
/* 8519C 800CEDDC 3F666666 */ .float 0.8999999762

glabel D_race_800CEDE0
/* 851A0 800CEDE0 42C80000 */ .float 100

glabel D_race_800CEDE4
/* 851A4 800CEDE4 47742400 */ .float 62500

glabel D_race_800CEDE8
/* 851A8 800CEDE8 3F6E147B */ .float 0.9300000072

glabel D_race_800CEDEC
/* 851AC 800CEDEC 481C4000 */ .float 160000

glabel D_race_800CEDF0
/* 851B0 800CEDF0 3F19999A */ .float 0.6000000238

glabel D_race_800CEDF4
/* 851B4 800CEDF4 3F733333 */ .float 0.9499999881

glabel D_race_800CEDF8
/* 851B8 800CEDF8 481C4000 */ .float 160000

glabel D_race_800CEDFC
/* 851BC 800CEDFC 3F666666 */ .float 0.8999999762

glabel D_race_800CEE00
/* 851C0 800CEE00 */ .asciz "magnet"
                      .balign 4

glabel D_race_800CEE08
/* 851C8 800CEE08 */ .asciz "magring"
                      .balign 4

glabel D_race_800CEE10
/* 851D0 800CEE10 */ .asciz "insd"
                      .balign 4

glabel D_race_800CEE18
/* 851D8 800CEE18 */ .asciz "curse"
                      .balign 4

glabel D_race_800CEE20
/* 851E0 800CEE20 */ .asciz "cgreen"
                      .balign 4

glabel D_race_800CEE28
/* 851E8 800CEE28 */ .asciz "cgreen2"
                      .balign 4

glabel D_race_800CEE30
/* 851F0 800CEE30 646D6973 */ .word 0x646D6973
/* 851F4 800CEE34 73696C00 */ .word 0x73696C00

glabel D_race_800CEE38
/* 851F8 800CEE38 */ .asciz "shield0"
                      .balign 4

glabel D_race_800CEE40
/* 85200 800CEE40 */ .asciz "shldin0"
                      .balign 4

glabel D_race_800CEE48
/* 85208 800CEE48 */ .asciz "shield1"
                      .balign 4

glabel D_race_800CEE50
/* 85210 800CEE50 */ .asciz "shldin1"
                      .balign 4

glabel D_race_800CEE58
/* 85218 800CEE58 */ .asciz "shield2"
                      .balign 4

glabel D_race_800CEE60
/* 85220 800CEE60 */ .asciz "shldin2"
                      .balign 4

glabel D_race_800CEE68
/* 85228 800CEE68 */ .asciz "shield3"
                      .balign 4

glabel D_race_800CEE70
/* 85230 800CEE70 */ .asciz "shldin3"
                      .balign 4

glabel D_race_800CEE78
/* 85238 800CEE78 */ .asciz "warpprt"
                      .balign 4

glabel D_race_800CEE80
/* 85240 800CEE80 3B83126F */ .float 0.00400000019

glabel D_race_800CEE84
/* 85244 800CEE84 3E4CCCCD */ .float 0.200000003

glabel D_race_800CEE88
/* 85248 800CEE88 7CF0BDC2 */ .float 9.999999934e+36

glabel D_race_800CEE8C
/* 8524C 800CEE8C 48742400 */ .float 250000

glabel D_race_800CEE90
/* 85250 800CEE90 00000000 */ .word 0x00000000
/* 85254 800CEE94 00000000 */ .word 0x00000000
/* 85258 800CEE98 00000000 */ .word 0x00000000
/* 8525C 800CEE9C 8007DD84 */ .word func_8007DD84
/* 85260 800CEEA0 00000000 */ .word 0x00000000
/* 85264 800CEEA4 8007DD8C */ .word func_8007DD8C
/* 85268 800CEEA8 00000000 */ .word 0x00000000
/* 8526C 800CEEAC 8007DD94 */ .word func_8007DD94
/* 85270 800CEEB0 00000000 */ .word 0x00000000
/* 85274 800CEEB4 8007DDB4 */ .word func_8007DDB4
/* 85278 800CEEB8 00000000 */ .word 0x00000000
/* 8527C 800CEEBC 80007834 */ .word func_80007834
/* 85280 800CEEC0 00000000 */ .word 0x00000000
/* 85284 800CEEC4 8000783C */ .word func_8000783C
/* 85288 800CEEC8 00000000 */ .word 0x00000000
/* 8528C 800CEECC 8012D6F0 */ .word func_race_8012D6F0
/* 85290 800CEED0 00000000 */ .word 0x00000000
/* 85294 800CEED4 80006624 */ .word func_80006624
/* 85298 800CEED8 00000000 */ .word 0x00000000
/* 8529C 800CEEDC 80009534 */ .word func_80009534
/* 852A0 800CEEE0 00000000 */ .word 0x00000000
/* 852A4 800CEEE4 80006928 */ .word func_80006928
/* 852A8 800CEEE8 00000000 */ .word 0x00000000
/* 852AC 800CEEEC 80006CBC */ .word func_80006CBC
/* 852B0 800CEEF0 00000000 */ .word 0x00000000
/* 852B4 800CEEF4 800073F4 */ .word func_800073F4
/* 852B8 800CEEF8 00000000 */ .word 0x00000000
/* 852BC 800CEEFC 800075B0 */ .word func_800075B0
/* 852C0 800CEF00 00000000 */ .word 0x00000000
/* 852C4 800CEF04 8000771C */ .word func_8000771C
/* 852C8 800CEF08 00000000 */ .word 0x00000000
/* 852CC 800CEF0C 8007DEA0 */ .word func_8007DEA0
/* 852D0 800CEF10 00000000 */ .word 0x00000000
/* 852D4 800CEF14 8007DF68 */ .word func_8007DF68
/* 852D8 800CEF18 00000000 */ .word 0x00000000
/* 852DC 800CEF1C 8000C2E0 */ .word func_8000C2E0
/* 852E0 800CEF20 00000000 */ .word 0x00000000
/* 852E4 800CEF24 8000C2E8 */ .word func_8000C2E8
/* 852E8 800CEF28 00000000 */ .word 0x00000000
/* 852EC 800CEF2C 8000C304 */ .word func_8000C304
/* 852F0 800CEF30 00000000 */ .word 0x00000000
/* 852F4 800CEF34 8000C2F4 */ .word func_8000C2F4
/* 852F8 800CEF38 00000000 */ .word 0x00000000
/* 852FC 800CEF3C 8000C2FC */ .word func_8000C2FC
