.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.2 */

glabel D_race_800CF0E0
/* 854A0 800CF0E0 */ .asciz "TurboL0"
                      .balign 4

glabel D_race_800CF0E8
/* 854A8 800CF0E8 */ .asciz "turb0f1"
                      .balign 4

glabel D_race_800CF0F0
/* 854B0 800CF0F0 */ .asciz "turb0f2"
                      .balign 4

glabel D_race_800CF0F8
/* 854B8 800CF0F8 */ .asciz "TurboL1"
                      .balign 4

glabel D_race_800CF100
/* 854C0 800CF100 */ .asciz "turb1f1"
                      .balign 4

glabel D_race_800CF108
/* 854C8 800CF108 */ .asciz "turb1f2"
                      .balign 4

glabel D_race_800CF110
/* 854D0 800CF110 */ .asciz "TurboL2"
                      .balign 4

glabel D_race_800CF118
/* 854D8 800CF118 */ .asciz "turb2f1"
                      .balign 4

glabel D_race_800CF120
/* 854E0 800CF120 */ .asciz "turb2f2"
                      .balign 4

glabel D_race_800CF128
/* 854E8 800CF128 43960000 */ .float 300

glabel D_race_800CF12C
/* 854EC 800CF12C 3F800000 */ .float 1

glabel D_race_800CF130
/* 854F0 800CF130 41F00000 */ .float 30

glabel D_race_800CF134
/* 854F4 800CF134 */ .asciz "trbsmke"
                      .balign 4

glabel D_race_800CF13C
/* 854FC 800CF13C C0000000 */ .float -2

glabel D_race_800CF140
/* 85500 800CF140 40400000 */ .float 3

glabel D_race_800CF144
/* 85504 800CF144 3F333333 */ .float 0.6999999881

glabel D_race_800CF148
/* 85508 800CF148 C0000000 */ .float -2

glabel D_race_800CF14C
/* 8550C 800CF14C 40400000 */ .float 3

glabel D_race_800CF150
/* 85510 800CF150 BF800000 */ .float -1

glabel D_race_800CF154
/* 85514 800CF154 43AF0000 */ .float 350

glabel D_race_800CF158
/* 85518 800CF158 433F0000 */ .float 191

glabel D_race_800CF15C
/* 8551C 800CF15C 43960000 */ .float 300

glabel D_race_800CF160
/* 85520 800CF160 3E4CCCCD */ .float 0.200000003

glabel D_race_800CF164
/* 85524 800CF164 3F19999A */ .float 0.6000000238

glabel D_race_800CF168
/* 85528 800CF168 3F800000 */ .float 1

glabel D_race_800CF16C
/* 8552C 800CF16C 43960000 */ .float 300

glabel D_race_800CF170
/* 85530 800CF170 3E4CCCCD */ .float 0.200000003

glabel D_race_800CF174
/* 85534 800CF174 3F19999A */ .float 0.6000000238

glabel D_race_800CF178
/* 85538 800CF178 3F800000 */ .float 1
/* 8553C 800CF17C 00000000 */ .float 0

glabel D_race_800CF180
/* 85540 800CF180 00000000 */ .word 0x00000000
/* 85544 800CF184 00000000 */ .word 0x00000000
/* 85548 800CF188 00000000 */ .word 0x00000000
/* 8554C 800CF18C 8011FAB4 */ .word func_race_8011FAB4
/* 85550 800CF190 00000000 */ .word 0x00000000
/* 85554 800CF194 8012E8CC */ .word func_race_8012E8CC
/* 85558 800CF198 00000000 */ .word 0x00000000
/* 8555C 800CF19C 8012F068 */ .word func_race_8012F068
/* 85560 800CF1A0 00000000 */ .word 0x00000000
/* 85564 800CF1A4 8012F4DC */ .word func_race_8012F4DC
/* 85568 800CF1A8 00000000 */ .word 0x00000000
/* 8556C 800CF1AC 8012F534 */ .word func_race_8012F534
/* 85570 800CF1B0 00000000 */ .word 0x00000000
/* 85574 800CF1B4 8012F67C */ .word func_race_8012F67C
/* 85578 800CF1B8 00000000 */ .word 0x00000000
/* 8557C 800CF1BC 8012F994 */ .word func_race_8012F994
/* 85580 800CF1C0 00000000 */ .word 0x00000000
/* 85584 800CF1C4 8012F868 */ .word func_race_8012F868
