.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_race_801324D0
/* E8890 801324D0 */ .word 0xFFFFFFFF
/* E8894 801324D4 */ .word 0x00000000
/* E8898 801324D8 */ .word 0x00000000
/* E889C 801324DC */ .word 0x00000000
/* E88A0 801324E0 */ .word 0x00000000
/* E88A4 801324E4 */ .word 0x00000000
/* E88A8 801324E8 */ .word 0x00000000
/* E88AC 801324EC */ .word 0x00000000
