.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.8.0 */

glabel D_race_800CF380
/* 85740 800CF380 3B800000 */ .float 0.00390625

glabel D_race_800CF384
/* 85744 800CF384 3D800000 */ .float 0.0625

glabel D_race_800CF388
/* 85748 800CF388 3C010204 */ .float 0.007874015719

glabel D_race_800CF38C
/* 8574C 800CF38C 3E000000 */ .float 0.125

glabel D_race_800CF390
/* 85750 800CF390 3E000000 */ .float 0.125
