FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

# Download wibo and make it executable
RUN wget https://github.com/decompals/wibo/releases/download/0.6.16/wibo -O /usr/local/bin/wibo && \
    chmod +x /usr/local/bin/wibo


