.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_800CA7D0
/* E88C0 800CA7D0 3F800000 */ .float 1

glabel D_menu_800CA7D4
/* E88C4 800CA7D4 BBA3D70A */ .float -0.004999999888

glabel D_menu_800CA7D8
/* E88C8 800CA7D8 3BA3D70A */ .float 0.004999999888

glabel D_menu_800CA7DC
/* E88CC 800CA7DC 3F800000 */ .float 1

glabel D_menu_800CA7E0
/* E88D0 800CA7E0 3F800000 */ .float 1
