.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126990
/* 144A80 80126990 */ .word 0x00000001
/* 144A84 80126994 */ .word 0x00000002

glabel D_menu_80126998
/* 144A88 80126998 */ .word 0xFFFFFFFF
