.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_801269A0
/* 144A90 801269A0 */ .word 0x00000001
/* 144A94 801269A4 */ .word 0x00000002

glabel D_menu_801269A8
/* 144A98 801269A8 */ .word 0xFFFFFFFF

glabel D_menu_801269AC
/* 144A9C 801269AC */ .word 0xFFFFFFFF

glabel D_menu_801269B0
/* 144AA0 801269B0 */ .word 0xFFFFFFFF
