.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_801269C0
/* 144AB0 801269C0 */ .word 0x00000001
/* 144AB4 801269C4 */ .word 0x00000002

glabel D_menu_801269C8
/* 144AB8 801269C8 */ .word 0xFFFFFFFF
