.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_801269D0
/* 144AC0 801269D0 */ .word 0xFFFFFFFF

glabel D_menu_801269D4
/* 144AC4 801269D4 */ .word 0x00000000
