.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126BE0
/* 144CD0 80126BE0 */ .word 0x00000001
/* 144CD4 80126BE4 */ .word 0x00000002

glabel D_menu_80126BE8
/* 144CD8 80126BE8 */ .word 0xFFFFFFFF
