.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126FB0
/* 1450A0 80126FB0 */ .word 0x00000001
/* 1450A4 80126FB4 */ .word 0x00000002

glabel D_menu_80126FB8
/* 1450A8 80126FB8 */ .word 0xFFFFFFFF
