.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126B90
/* 144C80 80126B90 */ .word 0x00000000

glabel D_menu_80126B94
/* 144C84 80126B94 */ .word 0x00000400

glabel D_menu_80126B98
/* 144C88 80126B98 */ .word 0x00000040

glabel D_menu_80126B9C
/* 144C8C 80126B9C */ .word 0x00000009

glabel D_menu_80126BA0
/* 144C90 80126BA0 */ .word 0xFFFFFFFF
