.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126BB0
/* 144CA0 80126BB0 */ .word 0x0000FFFF
/* 144CA4 80126BB4 */ .word func_menu_800ED394
/* 144CA8 80126BB8 */ .word 0x0000FFFF
/* 144CAC 80126BBC */ .word func_menu_800ED408
/* 144CB0 80126BC0 */ .word 0x00000001
/* 144CB4 80126BC4 */ .word 0x00000002
