.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_800CBD70
/* E9E60 800CBD70 4D454E55 */ .word 0x4D454E55
/* E9E64 800CBD74 44415441 */ .word 0x44415441
/* E9E68 800CBD78 00000000 */ .word 0x00000000

glabel D_menu_800CBD7C
/* E9E6C 800CBD7C BF800000 */ .float -1

glabel D_menu_800CBD80
/* E9E70 800CBD80 3F800000 */ .float 1

glabel D_menu_800CBD84
/* E9E74 800CBD84 00000000 */ .word 0x00000000

glabel D_menu_800CBD88
/* E9E78 800CBD88 */ .asciz "legomsc"
                      .balign 4

glabel D_menu_800CBD90
/* E9E80 800CBD90 */ .asciz "UISOUND"
                      .balign 4

glabel D_menu_800CBD98
/* E9E88 800CBD98 */ .asciz "GImages"
                      .balign 4

glabel D_menu_800CBDA0
/* E9E90 800CBDA0 */ .asciz "LEGORace"
                      .balign 4

glabel D_menu_800CBDAC
/* E9E9C 800CBDAC */ .asciz "menuname.srf"
                      .balign 4

glabel D_menu_800CBDBC
/* E9EAC 800CBDBC */ .asciz "menutext.srf"
                      .balign 4

glabel D_menu_800CBDCC
/* E9EBC 800CBDCC */ .asciz "circuit.srf"
                      .balign 4

glabel D_menu_800CBDD8
/* E9EC8 800CBDD8 */ .asciz "iolname.srf"
                      .balign 4

glabel D_menu_800CBDE4
/* E9ED4 800CBDE4 */ .asciz "GFonts"
                      .balign 4

glabel D_menu_800CBDEC
/* E9EDC 800CBDEC */ .asciz "gstyles"
                      .balign 4

glabel D_menu_800CBDF4
/* E9EE4 800CBDF4 */ .asciz "c6"
                      .balign 4

glabel D_menu_800CBDF8
/* E9EE8 800CBDF8 4D454E55 */ .word 0x4D454E55
/* E9EEC 800CBDFC 44415441 */ .word 0x44415441
/* E9EF0 800CBE00 5C504945 */ .word 0x5C504945
/* E9EF4 800CBE04 43454442 */ .word 0x43454442
/* E9EF8 800CBE08 00000000 */ .word 0x00000000

glabel D_menu_800CBE0C
/* E9EFC 800CBE0C 4C506965 */ .word 0x4C506965
/* E9F00 800CBE10 63654C6F */ .word 0x63654C6F
/* E9F04 800CBE14 2E6C6567 */ .word 0x2E6C6567
/* E9F08 800CBE18 00000000 */ .word 0x00000000

glabel D_menu_800CBE1C
/* E9F0C 800CBE1C 4C506965 */ .word 0x4C506965
/* E9F10 800CBE20 63654C6F */ .word 0x63654C6F
/* E9F14 800CBE24 2E574446 */ .word 0x2E574446
/* E9F18 800CBE28 00000000 */ .word 0x00000000

glabel D_menu_800CBE2C
/* E9F1C 800CBE2C 4C5F436F */ .word 0x4C5F436F
/* E9F20 800CBE30 6C6F7273 */ .word 0x6C6F7273
/* E9F24 800CBE34 2E4C4547 */ .word 0x2E4C4547
/* E9F28 800CBE38 00000000 */ .word 0x00000000

glabel D_menu_800CBE3C
/* E9F2C 800CBE3C BF800000 */ .float -1

glabel D_menu_800CBE40
/* E9F30 800CBE40 */ .asciz "MENUDATA\\PARTDB"
                      .balign 4

glabel D_menu_800CBE50
/* E9F40 800CBE50 */ .asciz "bodypart.pcf"
                      .balign 4

glabel D_menu_800CBE60
/* E9F50 800CBE60 */ .asciz "LPieceHi.leg"
                      .balign 4

glabel D_menu_800CBE70
/* E9F60 800CBE70 */ .asciz "LPieceHi.WDF"
                      .balign 4

glabel D_menu_800CBE80
/* E9F70 800CBE80 */ .asciz "crstmgr.leg"
                      .balign 4

glabel D_menu_800CBE8C
/* E9F7C 800CBE8C */ .asciz "chassis.cmf"
                      .balign 4

glabel D_menu_800CBE98
/* E9F88 800CBE98 7CF0BDC2 */ .float 9.999999934e+36

glabel D_menu_800CBE9C
/* E9F8C 800CBE9C 437F0000 */ .float 255

glabel D_menu_800CBEA0
/* E9F90 800CBEA0 00000000 */ .word 0x00000000
/* E9F94 800CBEA4 00000000 */ .word 0x00000000
/* E9F98 800CBEA8 00000000 */ .word 0x00000000
/* E9F9C 800CBEAC 800F20C4 */ .word func_menu_800F20C4
/* E9FA0 800CBEB0 00000000 */ .word 0x00000000
/* E9FA4 800CBEB4 8007BE18 */ .word func_8007BE18
/* E9FA8 800CBEB8 00000000 */ .word 0x00000000
/* E9FAC 800CBEBC 8007BE20 */ .word func_8007BE20
/* E9FB0 800CBEC0 00000000 */ .word 0x00000000
/* E9FB4 800CBEC4 8007BE28 */ .word func_8007BE28
/* E9FB8 800CBEC8 00000000 */ .word 0x00000000
/* E9FBC 800CBECC 8007BE30 */ .word func_8007BE30
/* E9FC0 800CBED0 00000000 */ .word 0x00000000
/* E9FC4 800CBED4 8007BE38 */ .word func_8007BE38
/* E9FC8 800CBED8 00000000 */ .word 0x00000000
/* E9FCC 800CBEDC 8007BE40 */ .word func_8007BE40
/* E9FD0 800CBEE0 00000000 */ .word 0x00000000
/* E9FD4 800CBEE4 8007BE48 */ .word func_8007BE48
/* E9FD8 800CBEE8 00000000 */ .word 0x00000000
/* E9FDC 800CBEEC 8007BE50 */ .word func_8007BE50
/* E9FE0 800CBEF0 00000000 */ .word 0x00000000
/* E9FE4 800CBEF4 8007BE58 */ .word func_8007BE58
/* E9FE8 800CBEF8 00000000 */ .word 0x00000000
/* E9FEC 800CBEFC 8007BE60 */ .word func_8007BE60
/* E9FF0 800CBF00 00000000 */ .word 0x00000000
/* E9FF4 800CBF04 8007BE68 */ .word func_8007BE68
/* E9FF8 800CBF08 00000000 */ .word 0x00000000
/* E9FFC 800CBF0C 800EF6A0 */ .word func_menu_800EF6A0

glabel D_menu_800CBF10
/* EA000 800CBF10 */ .asciz "MENUDATA\\"
                      .balign 4
/* EA00C 800CBF1C */ .asciz "english"
                      .balign 4
/* EA014 800CBF24 */ .asciz "spanish"
                      .balign 4
/* EA01C 800CBF2C */ .asciz "french"
                      .balign 4
/* EA024 800CBF34 */ .asciz "german"
                      .balign 4
/* EA02C 800CBF3C */ .asciz "italian"
                      .balign 4
/* EA034 800CBF44 */ .asciz "danish"
                      .balign 4
/* EA03C 800CBF4C */ .asciz "swedish"
                      .balign 4
/* EA044 800CBF54 */ .asciz "norwegi"
                      .balign 4
/* EA04C 800CBF5C */ .asciz "dutch"
                      .balign 4
/* EA054 800CBF64 */ .asciz "finnish"
                      .balign 4
