.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126C00
/* 144CF0 80126C00 */ .word 0x00000001
/* 144CF4 80126C04 */ .word 0x00000002

glabel D_menu_80126C08
/* 144CF8 80126C08 */ .word 0xFFFFFFFF

glabel D_menu_80126C0C
/* 144CFC 80126C0C */ .word 0x3D23D70A
/* 144D00 80126C10 */ .word 0x3D23D70A
/* 144D04 80126C14 */ .word 0x3D23D70A
/* 144D08 80126C18 */ .word 0x3D23D70A
/* 144D0C 80126C1C */ .word 0x3EC7AE14
/* 144D10 80126C20 */ .word 0x3ECCCCCD
/* 144D14 80126C24 */ .word 0x3D23D70A
