.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126C30
/* 144D20 80126C30 */ .word 0x800CBF1C
/* 144D24 80126C34 */ .word 0x800CBF24
/* 144D28 80126C38 */ .word 0x800CBF2C
/* 144D2C 80126C3C */ .word 0x800CBF34
/* 144D30 80126C40 */ .word 0x800CBF3C
/* 144D34 80126C44 */ .word 0x800CBF44
/* 144D38 80126C48 */ .word 0x800CBF4C
/* 144D3C 80126C4C */ .word 0x800CBF54
/* 144D40 80126C50 */ .word 0x800CBF5C
/* 144D44 80126C54 */ .word 0x800CBF64
