.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126C70
/* 144D60 80126C70 */ .word 0x800CC080

glabel D_menu_80126C74
/* 144D64 80126C74 */ .word 0x800CC08C
