.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_80126EF0
/* 144FE0 80126EF0 */ .word 0x00000001
/* 144FE4 80126EF4 */ .word 0x00000002

glabel D_menu_80126EF8
/* 144FE8 80126EF8 */ .word 0x3000000C
/* 144FEC 80126EFC */ .word 0x30000008
/* 144FF0 80126F00 */ .word 0x30000009
/* 144FF4 80126F04 */ .word 0x3000000A
/* 144FF8 80126F08 */ .word 0x3000000B
