.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_80126F50
/* 145040 80126F50 */ .word 0x00000001
/* 145044 80126F54 */ .word 0x00000002

glabel D_menu_80126F58
/* 145048 80126F58 */ .word 0x00000000
