.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_80126F60
/* 145050 80126F60 */ .word 0x00000001
/* 145054 80126F64 */ .word 0x00000002

glabel D_menu_80126F68
/* 145058 80126F68 */ .short 0x007C
/* 14505A 80126F6A */ .short 0x007D
/* 14505C 80126F6C */ .short 0x007E
/* 14505E 80126F6E */ .short 0x00DF
/* 145060 80126F70 */ .short 0x0089
/* 145062 80126F72 */ .short 0x008A
/* 145064 80126F74 */ .short 0x0080
/* 145066 80126F76 */ .short 0x0081

glabel D_menu_80126F78
/* 145068 80126F78 */ .short 0x0084
/* 14506A 80126F7A */ .short 0x0088
/* 14506C 80126F7C */ .short 0x0086
/* 14506E 80126F7E */ .short 0x0087
/* 145070 80126F80 */ .short 0x0000
/* 145072 80126F82 */ .short 0x0001
/* 145074 80126F84 */ .short 0x0000
/* 145076 80126F86 */ .short 0x0002
