.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80126FD0
/* 1450C0 80126FD0 */ .word 0x00000001
/* 1450C4 80126FD4 */ .word 0x00000002
/* 1450C8 80126FD8 */ .word 0x00000000

glabel D_menu_80126FDC
/* 1450CC 80126FDC */ .byte 0x13
/* 1450CD 80126FDD */ .byte 0x12
/* 1450CE 80126FDE */ .byte 0x16
/* 1450CF 80126FDF */ .byte 0x15
/* 1450D0 80126FE0 */ .byte 0x14
/* 1450D1 80126FE1 */ .byte 0x17
/* 1450D2 80126FE2 */ .byte 0x00
/* 1450D3 80126FE3 */ .byte 0x00
