.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_801270E0
/* 1451D0 801270E0 */ .word 0x00000001
/* 1451D4 801270E4 */ .word 0x00000002

glabel D_menu_801270E8
/* 1451D8 801270E8 */ .word 0xADADADFF
/* 1451DC 801270EC */ .word 0xFFDF00FF
/* 1451E0 801270F0 */ .word 0xE6DCB4FF
/* 1451E4 801270F4 */ .word 0x253DDFFF
/* 1451E8 801270F8 */ .word 0xDA1F1FFF

glabel D_menu_801270FC
/* 1451EC 801270FC */ .byte 0x01
/* 1451ED 801270FD */ .byte 0x00
/* 1451EE 801270FE */ .byte 0x03
/* 1451EF 801270FF */ .byte 0x02
/* 1451F0 80127100 */ .byte 0x01
/* 1451F1 80127101 */ .byte 0x00
/* 1451F2 80127102 */ .byte 0x03
/* 1451F3 80127103 */ .byte 0x02
/* 1451F4 80127104 */ .byte 0x00
/* 1451F5 80127105 */ .byte 0x01
/* 1451F6 80127106 */ .byte 0x02
/* 1451F7 80127107 */ .byte 0x03
/* 1451F8 80127108 */ .byte 0x02
/* 1451F9 80127109 */ .byte 0x00
/* 1451FA 8012710A */ .byte 0x03
/* 1451FB 8012710B */ .byte 0x01
/* 1451FC 8012710C */ .byte 0x02
/* 1451FD 8012710D */ .byte 0x00
/* 1451FE 8012710E */ .byte 0x03
/* 1451FF 8012710F */ .byte 0x01
/* 145200 80127110 */ .byte 0x03
/* 145201 80127111 */ .byte 0x01
/* 145202 80127112 */ .byte 0x02
/* 145203 80127113 */ .byte 0x00
/* 145204 80127114 */ .byte 0x04
/* 145205 80127115 */ .byte 0x00
/* 145206 80127116 */ .byte 0x00
/* 145207 80127117 */ .byte 0x00
