.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.2 */

glabel D_menu_80127150
/* 145240 80127150 */ .word 0xFFFFFFFF

glabel D_menu_80127154
/* 145244 80127154 */ .word D_menu_800CFED0
