.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_800CFED0
/* EDFC0 800CFED0 */ .asciz "Dialog.mid"
                      .balign 4

glabel D_menu_800CFEDC
/* EDFCC 800CFEDC 00000000 */ .word 0x00000000
