.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.8.0 */

glabel D_menu_80127160
/* 145250 80127160 */ .word 0x00000000

glabel D_menu_80127164
/* 145254 80127164 */ .word 0x00000000
