.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.2 */

glabel D_80000550
/* 1150 80000550 */ .asciz "Not a error"
                      .balign 4
/* 115C 8000055C */ .asciz "General I/O error"
                      .balign 4
/* 1170 80000570 */ .asciz "Invalid parameter"
                      .balign 4
/* 1184 80000584 */ .asciz "Invalid value"
                      .balign 4
/* 1194 80000594 */ .asciz "Out of memory error"
                      .balign 4
/* 11A8 800005A8 */ .asciz "I/O Busy error"
                      .balign 4
/* 11B8 800005B8 */ .asciz "Operation not supported"
                      .balign 4
/* 11D0 800005D0 */ .asciz "File not open"
                      .balign 4
/* 11E0 800005E0 */ .asciz "File not found"
                      .balign 4
/* 11F0 800005F0 */ .asciz "Access denied"
                      .balign 4
/* 1200 80000600 */ .asciz "File already exists"
                      .balign 4
/* 1214 80000614 */ .asciz "Exceeded maximum files open"
                      .balign 4
/* 1230 80000630 */ .asciz "Invalid name"
                      .balign 4
/* 1240 80000640 */ .asciz "Unable to read"
                      .balign 4
/* 1250 80000650 */ .asciz "Unable to write"
                      .balign 4
/* 1260 80000660 */ .asciz "Unable to seek"
                      .balign 4
/* 1270 80000670 */ .asciz "Attempt to read past file end"
                      .balign 4
/* 1290 80000690 */ .asciz "Invalid character encoutered"
                      .balign 4

glabel D_800006B0
/* 12B0 800006B0 00000000 */ .word 0x00000000

glabel D_800006B4
/* 12B4 800006B4 */ .asciz "\\"
                      .balign 4

glabel D_800006B8
/* 12B8 800006B8 00000000 */ .word 0x00000000
/* 12BC 800006BC 00000000 */ .word 0x00000000
/* 12C0 800006C0 00000000 */ .word 0x00000000
/* 12C4 800006C4 80002874 */ .word func_80002874
/* 12C8 800006C8 00000000 */ .word 0x00000000
/* 12CC 800006CC 80002874 */ .word func_80002874
/* 12D0 800006D0 00000000 */ .word 0x00000000
/* 12D4 800006D4 80002874 */ .word func_80002874
/* 12D8 800006D8 00000000 */ .word 0x00000000
/* 12DC 800006DC 80002874 */ .word func_80002874
/* 12E0 800006E0 00000000 */ .word 0x00000000
/* 12E4 800006E4 80007834 */ .word func_80007834
/* 12E8 800006E8 00000000 */ .word 0x00000000
/* 12EC 800006EC 8000783C */ .word func_8000783C
/* 12F0 800006F0 00000000 */ .word 0x00000000
/* 12F4 800006F4 800062F4 */ .word func_800062F4
/* 12F8 800006F8 00000000 */ .word 0x00000000
/* 12FC 800006FC 80006624 */ .word func_80006624
/* 1300 80000700 00000000 */ .word 0x00000000
/* 1304 80000704 80006858 */ .word func_80006858
/* 1308 80000708 00000000 */ .word 0x00000000
/* 130C 8000070C 80006928 */ .word func_80006928
/* 1310 80000710 00000000 */ .word 0x00000000
/* 1314 80000714 80006CBC */ .word func_80006CBC
/* 1318 80000718 00000000 */ .word 0x00000000
/* 131C 8000071C 800073F4 */ .word func_800073F4
/* 1320 80000720 00000000 */ .word 0x00000000
/* 1324 80000724 800075B0 */ .word func_800075B0
/* 1328 80000728 00000000 */ .word 0x00000000
/* 132C 8000072C 8000771C */ .word func_8000771C

glabel D_80000730
/* 1330 80000730 00000000 */ .word 0x00000000
/* 1334 80000734 00000000 */ .word 0x00000000
/* 1338 80000738 00000000 */ .word 0x00000000
/* 133C 8000073C 80007EBC */ .word func_80007EBC
/* 1340 80000740 00000000 */ .word 0x00000000
/* 1344 80000744 80007F90 */ .word func_80007F90
/* 1348 80000748 00000000 */ .word 0x00000000
/* 134C 8000074C 80008064 */ .word func_80008064
/* 1350 80000750 00000000 */ .word 0x00000000
/* 1354 80000754 80007A64 */ .word func_80007A64
