.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.0 */

glabel D_800010D0
/* 1CD0 800010D0 3FFFFFD60E94EE39 */ .double 1.99995999999999996

glabel D_800010D8
/* 1CD8 800010D8 3FFFFEB0 */ .float 1.999959946

glabel D_800010DC
/* 1CDC 800010DC 47000000 */ .float 32768

glabel D_800010E0
/* 1CE0 800010E0 38000000 */ .float 3.051757812e-05

glabel D_800010E4
/* 1CE4 800010E4 43380000 */ .float 184
