.include "macro.inc"

.section .rdata

/* Generated by spimdisasm 1.8.0 */

glabel D_80001140
/* 1D40 80001140 3FE0000000000000 */ .double 0.5

glabel D_80001148
/* 1D48 80001148 412E848000000000 */ .double 1000000
