name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download rom
      run: |
        wget $N64_BASEROM_URL > baserom.z64
        shasum baserom.z64
      env:
        N64_BASEROM_URL: ${{ secrets.N64_BASEROM_URL }}
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
